apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanamation-com
  labels:
    app: nanamation-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanamation-com
  template:
    metadata:
      labels:
        app: nanamation-com
    spec:
      securityContext:
        fsGroup: 101  # for nginx
      volumes:
        - name: content
          emptyDir: {}
      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v3.6.6
          args:
            - -repo=https://github.com/hockin-org/nanamation.com
            - -root=/git
            - -branch=master
            - -depth=1
            - -wait=60
            - -dest=html
            - -max-sync-failures=1000000000
            - -v=2
          resources:
            requests:
              cpu: 25m
            limits:
              memory: 32Mi
          volumeMounts:
            - name: content
              mountPath: /git
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: 25m
            limits:
              memory: 16Mi
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 1
            failureThreshold: 2
