apiVersion: apps/v1
kind: Deployment
metadata:
  name: hockin-org-genealogy
  labels:
    app: hockin-org-genealogy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hockin-org-genealogy
  template:
    metadata:
      labels:
        app: hockin-org-genealogy
    spec:
      securityContext:
        fsGroup: 33  # for apache
      terminationGracePeriodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hockin-org-genealogy
      containers:
        - name: mysql
          image: mysql:5.7
          args:
            - --bind-address=127.0.0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hockin-org-genealogy-mysql
                  key: passwd
          resources:
            requests:
              cpu: 20m
            limits:
              memory: 300Mi
          volumeMounts:
            - name: data
              subPath: mysql
              mountPath: /var/lib/mysql
        - name: webtrees
          image: thockin/webtrees:v2.0.16-2
          resources:
            requests:
              cpu: 20m
            limits:
              memory: 300Mi
          volumeMounts:
            - name: data
              subPath: webtrees
              mountPath: /var/www/html/data
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 2
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
