apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hockin-org-genealogy
  labels:
    app: hockin-org-genealogy
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
