apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hockin
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hockin-org
    networking.gke.io/managed-certificates: hockin
    kubernetes.io/ingress.class: gce
spec:
  backend:
    serviceName: hockin-org
    servicePort: 80
  rules:
  - host: nanamation.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nanamation-com
          servicePort: 80
  - host: nanhockin.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: nanamation-com
          servicePort: 80
  - host: hockin.org
    http:
      paths:
        # FIXME: this is a hack until I decompose the contents into smaller
        # pieces, e.g. a backend bucket.
      - path: /~thockin
        backend:
          serviceName: hockin-org-thockin
          servicePort: 80
      - path: /~thockin/*
        backend:
          serviceName: hockin-org-thockin
          servicePort: 80
  - host: family.hockin.org
    http:
      paths:
      - path: /*
        backend:
          serviceName: hockin-org-genealogy
          servicePort: 80
