apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hockin-org-thockin
  labels:
    app: hockin-org-thockin
spec:
  replicas: 1
  # selector defaults from template labels
  template:
    metadata:
      labels:
        app: hockin-org-thockin
    spec:
      securityContext:
        fsGroup: 101  # for nginx
      terminationGracePeriodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hockin-org-thockin
        - name: nginx-conf
          configMap:
            name: hockin-org-thockin-nginx
            # Map all keys to files.
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: 25m
            limits:
              memory: 32Mi
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/~thockin
              readOnly: false # would be nice if this was git-sync'ed and everything big stored elsewhere
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 1
            failureThreshold: 2
