apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hockin-org-thockin
  labels:
    app: hockin-org-thockin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
