apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      securityContext:
        runAsUser: 1234
        runAsGroup: 1234
        fsGroup: 1234
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: MOTD
              value: "Disposable SMP"
            - name: MEMORY
              value: "1G"
            - name: REMOVE_OLD_MODS
              value: "TRUE"
            - name: ENABLE_RCON
              value: "true"
            - name: FORCE_REDOWNLOAD
              value: "false"
            - name: DIFFICULTY
              value: "normal"
            - name: OVERRIDE_SERVER_PROPERTIES
              value: "true"
            - name: OVERRIDE_WHITELIST
              value: "true"
            - name: WHITELIST
              value: "Apocalypse2121"
            - name: OPS
              value: ""
            - name: MAX_PLAYERS
              value: "10"
            - name: MAX_WORLD_SIZE
              value: "12000"
            - name: SNOOPER_ENABLED
              value: "false"
            - name: MODE
              value: "survival"
            - name: ONLINE_MODE
              value: "TRUE"
            - name: ALLOW_NETHER
              value: "true"
            - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
              value: "false"
            - name: ENABLE_COMMAND_BLOCK
              value: "true"
            - name: GENERATE_STRUCTURES
              value: "true"

            - name: SPAWN_ANIMALS
              value: "true"
            - name: SPAWN_MONSTERS
              value: "true"
            - name: SPAWN_NPCS
              value: "true"
            - name: PVP
              value: "true"
          ports:
            - name: minecraft
              containerPort: 25565
              hostPort: 25565
          resources:
            requests:
              cpu: 100m
              memory: 2Gi
            limits:
              memory: 3Gi
          volumeMounts:
            - name: data
              mountPath: /data
          startupProbe:
            exec:
              command: [ mc-monitor, status ]
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 3
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 25565
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 2
